language: go
go:
- 1.7.5
install:
- cd /tmp && curl -L https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz -o glide.tar.gz && tar -xf glide.tar.gz && mkdir -p $GOPATH/bin && mv linux-amd64/glide $GOPATH/bin/ && cd -
- go get golang.org/x/tools/cmd/cover
- go get -v github.com/axw/gocov/gocov
- go get -v github.com/mattn/goveralls
script:
- glide install
- ./test.sh
after_success:
- GOPATH=`pwd`:$GOPATH $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
