# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/boltdb/bolt"

[[constraint]]
  branch = "master"
  name = "github.com/chzyer/readline"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/gosigar"

[[constraint]]
  branch = "master"
  name = "github.com/codahale/hdrhistogram"

[[constraint]]
  branch = "master"
  name = "github.com/davecgh/go-spew"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/appdir"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/bytemap"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/errors"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/goexpr"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/golog"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/msgpack"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/mtime"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/sqlparser"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/tlsdefaults"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/tlsredis"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/uuid"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/vtime"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/wal"

[[constraint]]
  name = "github.com/getlantern/yaml"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/jmcvetta/randutil"

[[constraint]]
  branch = "master"
  name = "github.com/kylelemons/godebug"

[[constraint]]
  branch = "master"
  name = "github.com/oxtoacart/bpool"

[[constraint]]
  branch = "master"
  name = "github.com/oxtoacart/emsort"

[[constraint]]
  branch = "master"
  name = "github.com/retailnext/hllpp"

[[constraint]]
  branch = "master"
  name = "github.com/rickar/props"

[[constraint]]
  branch = "master"
  name = "github.com/spaolacci/murmur3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/vharitonsky/iniflags"

[[constraint]]
  name = "golang.org/x/net"
  source = "https://github.com/golang/net"

[[constraint]]
  name = "gopkg.in/redis.v5"
  version = "5.2.9"

[prune]
  go-tests = true
  unused-packages = true
