test:
  retentionperiod:  2h
  maxmemstorebytes: 500000000
  maxflushlatency:  5m
  sql: >
    SELECT
      SUM(i) AS i,
      SUM(ii) AS ii,
      AVG(ii) / AVG(i) AS iii
    FROM inbound
    GROUP BY period(5m)
